# Generated by Django 4.0.3 on 2022-03-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_c'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_c',
        ),
    ]
