# Generated by Django 4.0.4 on 2022-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_attributes_delete_atribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_list',
            field=models.TextField(default=1, verbose_name='Характеристики'),
            preserve_default=False,
        ),
    ]
